# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages(c("dplyr", "data.table", "dtplyr", "rtdists", "knitr"), repos = "http://cran.rstudio.com")'
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
